FROM neo4j:4.0.0-community
RUN apt-get update -y
RUN apt-get install -y nano
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get install -y screen
RUN mkdir /home/data
RUN mkdir /home/dependecies
COPY ./requirements.txt /home/dependecies
RUN pip3 install -r /home/dependecies/requirements.txt